### ISSUE TITLE
Would like it if Sprints were added as Milestones to 'Git Issues'

### ISSUE THREAD

**Issue by mikekoetter** [flying-donut/flying-donut-operations#11]
When a card that is tagged as a git issue is added to a sprint, It would be great if Flying Donut could set the github milestone for that issue to be that of the Sprint ( creating one if it doesn't exist )

**Comment by jtzikas** [comment]
Hi, the request is great but we have a conflict with our future plans. We are going to introduce milestones in Flying Donut and we where thinking in having them to integrate with the github ones.

The question is if you had milestones in Flying Donut would you still want to bind the sprints with the github milestones?

**Comment by mikekoetter** [comment]
How would the Milestones in Flying Donut be used?  What would the purpose be?

**Comment by jtzikas** [comment]
The idea is that you will be able to group sprints into a milestone. In a milestone you will be able to view all cards that are included in the sprints in one view.

**Comment by mikekoetter** [comment]
so any card linked with a github issue that is added to sprint grouped in a github linked milestone would have that milestone added in github issues?

**Comment by jtzikas** [comment]
Yes exactly. All cards that are linked to github will be added to the coresponding milestone in github

**Comment by mikekoetter** [comment]
that would be great

**Comment by mikekoetter** [comment]
Are you still planning to add milestones to Flying Donut?

**Comment by jtzikas** [comment]
Yes we are. It is planned for our next sprint.

**Comment by jtzikas** [comment]
Milestones are released and available to all our users. In order to get the milestones synced with github you need to unlink and re-link your project with the sync milestones option enabled. Your linked github issues will be moved to the corresponding flying donut milestone based on the sprint end dates. 

If there are some day/time differences you will see the linked github issues moved from one milestone to another. By adjusting the due date of the milestones, to include the expected sprints, you will have everything properly in place.
