### ISSUE TITLE
Enhancement - A function to hide past sprint

### ISSUE THREAD

**Issue by ghost** [flying-donut/flying-donut-operations#40]
I was curious if there could be a button to hide or delete specific past sprint in the sprint list, so that the list can be more neat when we have a lot of past sprints inside it. Thank you.

**Comment by jtzikas** [comment]
You can only delete empty sprints with no cards. We are thinking to introduce a "close" functionality where you can close the sprint and basically archive it so that no further work to be done, but it is not in our short term plans.

Currently in the sprints page, you should only see the active, future and the latest completed sprint, by default. If you click on the "Show All" button then you will see all past sprints of your project. Could it be that you have enabled it and you are showing all sprints of your project?

![image](https://cloud.githubusercontent.com/assets/2730604/25521531/a5524b5e-2c08-11e7-9a47-c063dd424900.png)

Let me know if this option is not working for your case.

Otherwise you could try to make use of the milestones functionality where you can group sprints by end date. That way when you go via the milestones page you will limit the number of sprints of your list. Have a look at our the [milestones page](https://www.flyingdonut.io/app/milestones/project-id=519363e1e4b0f8cb1e1b7610) of our public operations project to see if it fits your needs.

**Comment by jtzikas** [comment]
Hi @lees890119, I just wanted to check with you about the status of the issue. Did it work out or are you still in the need of a "hide sprint" functionality?

**Comment by jtzikas** [comment]
The new UI handles the sprints in a different way.  The sprints are shown in a timeline, thus the need to hide past sprints does not exist any more.
